name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to tag the release (e.g. 1.2.3)'
        required: true
        type: string

permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Test Report
      uses: dorny/test-reporter@v3
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: reports/jest-junit.xml    # Path to test results
        reporter: jest-junit        # Format of test results
    - name: Tag commit with version
      run: |
        git tag v${{ inputs.version }}
        git push origin v${{ inputs.version }}
